//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinguTools.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinguTools.Common.Resources.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chart has been modified since it was last opened. However, the old chart property will still be used..
        /// </summary>
        public static string Diag_chart_modified {
            get {
                return ResourceManager.GetString("Diag_chart_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different EX effects coexist at the same tick: {0}. The game may only display one of these..
        /// </summary>
        public static string Diag_concurrent_ex_effects {
            get {
                return ResourceManager.GetString("Diag_concurrent_ex_effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First argument must be a valid integer..
        /// </summary>
        public static string Diag_first_argument_must_int {
            get {
                return ResourceManager.GetString("Diag_first_argument_must_int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid joint type for {0}..
        /// </summary>
        public static string Diag_Invalid_joint_type_note {
            get {
                return ResourceManager.GetString("Diag_Invalid_joint_type_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no events found on main TIL {0}..
        /// </summary>
        public static string Diag_main_timeline_not_found {
            get {
                return ResourceManager.GetString("Diag_main_timeline_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;#override {0}&apos; requires at one argument or two arguments..
        /// </summary>
        public static string Diag_meta_override_arument_count_mismatch {
            get {
                return ResourceManager.GetString("Diag_meta_override_arument_count_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SortName was provided. A new SortName has been generated from the Title..
        /// </summary>
        public static string Diag_no_sortname_provided {
            get {
                return ResourceManager.GetString("Diag_no_sortname_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The note overlaps with note in other TILs. This may cause problems in the scroll speed of this note..
        /// </summary>
        public static string Diag_note_overlapped_in_different_TIL {
            get {
                return ResourceManager.GetString("Diag_note_overlapped_in_different_TIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preview start time is set later than 120 seconds. This may cause the game to freeze when selecting the song..
        /// </summary>
        public static string Diag_pv_laterthan_120 {
            get {
                return ResourceManager.GetString("Diag_pv_laterthan_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of this note is {0}. This might be due to nodes in the original note having spacing less than {1}..
        /// </summary>
        public static string Diag_set_length_smaller_than_unit {
            get {
                return ResourceManager.GetString("Diag_set_length_smaller_than_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage {0} with ID {1} already exists..
        /// </summary>
        public static string Diag_stage_already_exists {
            get {
                return ResourceManager.GetString("Diag_stage_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified StringID (id or str) {0} could not be found in &apos;{1}&apos;. Please check your input or run &quot;Recollect A000&quot; to refresh the database. If you want to use your custom StringID, please provide both (i.e. &quot;#meta ... [ID] [String]&quot;)..
        /// </summary>
        public static string Diag_string_id_not_found {
            get {
                return ResourceManager.GetString("Diag_string_id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Time Signature event was found at bar 0. Defaulting to a 4/4 time signature..
        /// </summary>
        public static string Diag_time_Signature_event_not_found_at_0 {
            get {
                return ResourceManager.GetString("Diag_time_Signature_event_not_found_at_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown tag &apos;{0}&apos;..
        /// </summary>
        public static string Diag_unknown_tag {
            get {
                return ResourceManager.GetString("Diag_unknown_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown property mark {0} at file position 0x{1:X2}, data: {2}..
        /// </summary>
        public static string Diag_Unrecognized_meta {
            get {
                return ResourceManager.GetString("Diag_Unrecognized_meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent of Air cannot be null..
        /// </summary>
        public static string Error_air_parent_null {
            get {
                return ResourceManager.GetString("Error_air_parent_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent of AirSlide cannot be null..
        /// </summary>
        public static string Error_air_slide_parent_null {
            get {
                return ResourceManager.GetString("Error_air_slide_parent_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file is not set..
        /// </summary>
        public static string Error_audio_file_is_not_set {
            get {
                return ResourceManager.GetString("Error_audio_file_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background File is not set..
        /// </summary>
        public static string Error_background_file_is_not_set {
            get {
                return ResourceManager.GetString("Error_background_file_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No BPM change event was found at tick 0..
        /// </summary>
        public static string Error_BPM_change_event_not_found_at_0 {
            get {
                return ResourceManager.GetString("Error_BPM_change_event_not_found_at_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file was not found..
        /// </summary>
        public static string Error_file_not_found {
            get {
                return ResourceManager.GetString("Error_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hold is missing a tail..
        /// </summary>
        public static string Error_hold_has_no_tail {
            get {
                return ResourceManager.GetString("Error_hold_has_no_tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Air parent is invalid..
        /// </summary>
        public static string Error_invalid_Air_parent {
            get {
                return ResourceManager.GetString("Error_invalid_Air_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified AirSlide parent is invalid..
        /// </summary>
        public static string Error_invalid_AirSlide_parent {
            get {
                return ResourceManager.GetString("Error_invalid_AirSlide_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audio format..
        /// </summary>
        public static string Error_invalid_audio {
            get {
                return ResourceManager.GetString("Error_invalid_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid effect image format..
        /// </summary>
        public static string Error_invalid_bg_fx_image {
            get {
                return ResourceManager.GetString("Error_invalid_bg_fx_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid background image format..
        /// </summary>
        public static string Error_invalid_bg_image {
            get {
                return ResourceManager.GetString("Error_invalid_bg_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header {0} in the chart file does not match {1}..
        /// </summary>
        public static string Error_Invalid_Header {
            get {
                return ResourceManager.GetString("Error_Invalid_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sample rate: {0}, required is 48000Hz..
        /// </summary>
        public static string Error_invalid_sample_rate_48000 {
            get {
                return ResourceManager.GetString("Error_invalid_sample_rate_48000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket file is not set..
        /// </summary>
        public static string Error_jacket_file_is_not_set {
            get {
                return ResourceManager.GetString("Error_jacket_file_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} chunks were found in the input file..
        /// </summary>
        public static string Error_no_chunks_found {
            get {
                return ResourceManager.GetString("Error_no_chunks_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note are incompatible for pairing..
        /// </summary>
        public static string Error_pairing_notes_incompatible {
            get {
                return ResourceManager.GetString("Error_pairing_notes_incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preview stop time must be greater than the start time..
        /// </summary>
        public static string Error_preview_stop_greater_than_start {
            get {
                return ResourceManager.GetString("Error_preview_stop_greater_than_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to read {0} bytes for {1} but only got {2}..
        /// </summary>
        public static string Error_Size_Incompatible {
            get {
                return ResourceManager.GetString("Error_Size_Incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SoflanArea is missing a tail..
        /// </summary>
        public static string Error_soflanArea_has_no_tail {
            get {
                return ResourceManager.GetString("Error_soflanArea_has_no_tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song ID is not set..
        /// </summary>
        public static string Error_song_id_is_not_set {
            get {
                return ResourceManager.GetString("Error_song_id_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage ID is not set..
        /// </summary>
        public static string Error_stage_id_is_not_set {
            get {
                return ResourceManager.GetString("Error_stage_id_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error_Unhandled {
            get {
                return ResourceManager.GetString("Error_Unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type {0} at file position 0x{1:X2}..
        /// </summary>
        public static string Error_Unrecognized_data_type {
            get {
                return ResourceManager.GetString("Error_Unrecognized_data_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown event mark {0} at file position0x{1:X2}..
        /// </summary>
        public static string Error_Unrecognized_event {
            get {
                return ResourceManager.GetString("Error_Unrecognized_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown note type {0} at file position 0x{1:X2}..
        /// </summary>
        public static string Error_Unrecognized_note_type {
            get {
                return ResourceManager.GetString("Error_Unrecognized_note_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afb Texture (*.afb)|*.afb.
        /// </summary>
        public static string Filefilter_afb {
            get {
                return ResourceManager.GetString("Filefilter_afb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunithm Chart (*.c2s)|*.c2s.
        /// </summary>
        public static string Filefilter_c2s {
            get {
                return ResourceManager.GetString("Filefilter_c2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectDraw Surface (*.dds)|*.dds.
        /// </summary>
        public static string Filefilter_dds {
            get {
                return ResourceManager.GetString("Filefilter_dds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable (*.exe)|*.exe.
        /// </summary>
        public static string Filefilter_exe {
            get {
                return ResourceManager.GetString("Filefilter_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.png;*.jpg;*.jpeg;*.webp)|*.png;*.jpg;*.jpeg;*.webp.
        /// </summary>
        public static string Filefilter_image {
            get {
                return ResourceManager.GetString("Filefilter_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margrete Chart (*.mgxc)|*.mgxc.
        /// </summary>
        public static string Filefilter_mgxc {
            get {
                return ResourceManager.GetString("Filefilter_mgxc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Files (*.wav;*.ogg;*.mp3)|*.wav;*.ogg;*.mp3.
        /// </summary>
        public static string Filefilter_sound {
            get {
                return ResourceManager.GetString("Filefilter_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to multiple overlapping Slide nodes existing simultaneously, it is unknown to determine from which Slide node the Air should start..
        /// </summary>
        public static string Overlapping_Air_Parent_Slide {
            get {
                return ResourceManager.GetString("Overlapping_Air_Parent_Slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting....
        /// </summary>
        public static string Status_collecting {
            get {
                return ResourceManager.GetString("Status_collecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting Track....
        /// </summary>
        public static string Status_Convert_cue_file {
            get {
                return ResourceManager.GetString("Status_Convert_cue_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting....
        /// </summary>
        public static string Status_converting {
            get {
                return ResourceManager.GetString("Status_converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting Audio....
        /// </summary>
        public static string Status_converting_audio {
            get {
                return ResourceManager.GetString("Status_converting_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting Chart....
        /// </summary>
        public static string Status_converting_chart {
            get {
                return ResourceManager.GetString("Status_converting_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting Jacket....
        /// </summary>
        public static string Status_converting_jacket {
            get {
                return ResourceManager.GetString("Status_converting_jacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Status_done {
            get {
                return ResourceManager.GetString("Status_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Status_error {
            get {
                return ResourceManager.GetString("Status_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting....
        /// </summary>
        public static string Status_extracting {
            get {
                return ResourceManager.GetString("Status_extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Status_idle {
            get {
                return ResourceManager.GetString("Status_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging....
        /// </summary>
        public static string Status_merging {
            get {
                return ResourceManager.GetString("Status_merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalizing....
        /// </summary>
        public static string Status_normalizing {
            get {
                return ResourceManager.GetString("Status_normalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing....
        /// </summary>
        public static string Status_parsing {
            get {
                return ResourceManager.GetString("Status_parsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Background....
        /// </summary>
        public static string Status_processing_background {
            get {
                return ResourceManager.GetString("Status_processing_background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Effects....
        /// </summary>
        public static string Status_processing_effects {
            get {
                return ResourceManager.GetString("Status_processing_effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading....
        /// </summary>
        public static string Status_reading {
            get {
                return ResourceManager.GetString("Status_reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Status_saving {
            get {
                return ResourceManager.GetString("Status_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string Status_Searching {
            get {
                return ResourceManager.GetString("Status_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string Status_starting {
            get {
                return ResourceManager.GetString("Status_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating....
        /// </summary>
        public static string Status_Validate {
            get {
                return ResourceManager.GetString("Status_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing....
        /// </summary>
        public static string Status_writing {
            get {
                return ResourceManager.GetString("Status_writing", resourceCulture);
            }
        }
    }
}
