//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinguTools.Chart.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinguTools.Chart.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The converted Crush has a minimum density of {0}. However, the original End of Crash is Control, resulting in the End actually being a Step..
        /// </summary>
        public static string Diag_AirCrush_min_density_but_end_Control {
            get {
                return ResourceManager.GetString("Diag_AirCrush_min_density_but_end_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different EX effects coexist at the tick {0}: {1}. The game may only display one of these..
        /// </summary>
        public static string Diag_concurrent_ex_effects {
            get {
                return ResourceManager.GetString("Diag_concurrent_ex_effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main TIL {0} was not found. A new TIL with an initial speed of 1.0 has been created..
        /// </summary>
        public static string Diag_main_timeline_not_found {
            get {
                return ResourceManager.GetString("Diag_main_timeline_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The note overlaps with note in other TILs. This may cause problems in the scroll speed of this note..
        /// </summary>
        public static string Diag_note_overlapped_in_different_TIL {
            get {
                return ResourceManager.GetString("Diag_note_overlapped_in_different_TIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to set the length of this note to {0}, but it has been constrained to the minimum value of {1}. This might be due to nodes in the original note having spacing less than {1}..
        /// </summary>
        public static string Diag_set_length_smaller_than_unit {
            get {
                return ResourceManager.GetString("Diag_set_length_smaller_than_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Time Signature event was found at bar 0. Defaulting to a 4/4 time signature..
        /// </summary>
        public static string Diag_time_Signature_event_not_found_at_0 {
            get {
                return ResourceManager.GetString("Diag_time_Signature_event_not_found_at_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent of Air cannot be null..
        /// </summary>
        public static string Error_air_parent_null {
            get {
                return ResourceManager.GetString("Error_air_parent_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent of AirSlide cannot be null..
        /// </summary>
        public static string Error_air_slide_parent_null {
            get {
                return ResourceManager.GetString("Error_air_slide_parent_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No BPM change event was found at tick 0..
        /// </summary>
        public static string Error_BPM_change_event_not_found_at_0 {
            get {
                return ResourceManager.GetString("Error_BPM_change_event_not_found_at_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Hold is missing a tail..
        /// </summary>
        public static string Error_hold_has_no_tail {
            get {
                return ResourceManager.GetString("Error_hold_has_no_tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Air parent is invalid..
        /// </summary>
        public static string Error_invalid_Air_parent {
            get {
                return ResourceManager.GetString("Error_invalid_Air_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified AirSlide parent is invalid..
        /// </summary>
        public static string Error_invalid_AirSlide_parent {
            get {
                return ResourceManager.GetString("Error_invalid_AirSlide_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll speed change events must have a non-negative TIL value..
        /// </summary>
        public static string Error_no_negative_timeline_event {
            get {
                return ResourceManager.GetString("Error_no_negative_timeline_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note must have a non-negative TIL value..
        /// </summary>
        public static string Error_note_must_have_non_negative_timeline {
            get {
                return ResourceManager.GetString("Error_note_must_have_non_negative_timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note are incompatible for pairing..
        /// </summary>
        public static string Error_pairing_notes_incompatible {
            get {
                return ResourceManager.GetString("Error_pairing_notes_incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SoflanArea is missing a tail..
        /// </summary>
        public static string Error_soflanArea_has_no_tail {
            get {
                return ResourceManager.GetString("Error_soflanArea_has_no_tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing....
        /// </summary>
        public static string Status_parsing {
            get {
                return ResourceManager.GetString("Status_parsing", resourceCulture);
            }
        }
    }
}
