//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinguTools.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinguTools.Localization.ModelStrings", typeof(ModelStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGM.
        /// </summary>
        public static string Category_BGM {
            get {
                return ResourceManager.GetString("Category_BGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Category_Chart {
            get {
                return ResourceManager.GetString("Category_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Category_Display {
            get {
                return ResourceManager.GetString("Category_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string Category_Misc {
            get {
                return ResourceManager.GetString("Category_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string Category_Song {
            get {
                return ResourceManager.GetString("Category_Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Category_Sync {
            get {
                return ResourceManager.GetString("Category_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World&apos;s End.
        /// </summary>
        public static string Category_WorldsEnd {
            get {
                return ResourceManager.GetString("Category_WorldsEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the best latency difference between converted audio and playback in Margrete/UMIGURI, please use .wav files..
        /// </summary>
        public static string Description_BGMFile {
            get {
                return ResourceManager.GetString("Description_BGMFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the starting BPM (Beats Per Minute) of the chart. It is used to calculate real offset..
        /// </summary>
        public static string Description_BgmInitialBpm {
            get {
                return ResourceManager.GetString("Description_BgmInitialBpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the time signature (beats per bar and note value) at the start of the chart. It is used to calculate real offset..
        /// </summary>
        public static string Description_BgmInitialTimeSignature {
            get {
                return ResourceManager.GetString("Description_BgmInitialTimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM displayed in song selection menu.
        /// </summary>
        public static string Description_DisplayBPM {
            get {
                return ResourceManager.GetString("Description_DisplayBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure this through Margrete (Insert a blank bar before the first measure). If enabled, a silent measure with click cues is inserted at the beginning, ensuring that the first musical measure follows the blank..
        /// </summary>
        public static string Description_InsertBlankMeasure {
            get {
                return ResourceManager.GetString("Description_InsertBlankMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure this through Margrete (Base Timeline). Determines which Timeline affects the bar line positions and AIR animation speed. Default is 0..
        /// </summary>
        public static string Description_MainTil {
            get {
                return ResourceManager.GetString("Description_MainTil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value represents the offset (in seconds) applied to the song manually set by user. Positive values indicate a delay, while negative values indicate an advance..
        /// </summary>
        public static string Description_ManualOffset {
            get {
                return ResourceManager.GetString("Description_ManualOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value represents the calculated offset (in seconds) applied to the song. Positive values indicate a delay, while negative values indicate an advance..
        /// </summary>
        public static string Description_RealOffset {
            get {
                return ResourceManager.GetString("Description_RealOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Song ID is extracted from Margrete&apos;s Song ID..
        /// </summary>
        public static string Description_SongId {
            get {
                return ResourceManager.GetString("Description_SongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how songs are sorted in the game..
        /// </summary>
        public static string Description_SortName {
            get {
                return ResourceManager.GetString("Description_SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the &quot;World&apos;s End&quot; event that unlocks the chart in the game..
        /// </summary>
        public static string Description_WorldsEndEventID {
            get {
                return ResourceManager.GetString("Description_WorldsEndEventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Display_Artist {
            get {
                return ResourceManager.GetString("Display_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background File.
        /// </summary>
        public static string Display_BackgroundFile {
            get {
                return ResourceManager.GetString("Display_BackgroundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Stage.
        /// </summary>
        public static string Display_BackgroundStage {
            get {
                return ResourceManager.GetString("Display_BackgroundStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGM File.
        /// </summary>
        public static string Display_BGMFile {
            get {
                return ResourceManager.GetString("Display_BGMFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial BPM.
        /// </summary>
        public static string Display_BgmInitialBpm {
            get {
                return ResourceManager.GetString("Display_BgmInitialBpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Time Signature.
        /// </summary>
        public static string Display_BgmInitialTimeSignature {
            get {
                return ResourceManager.GetString("Display_BgmInitialTimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Start Time (s).
        /// </summary>
        public static string Display_BgmPreviewStart {
            get {
                return ResourceManager.GetString("Display_BgmPreviewStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Stop Time (s).
        /// </summary>
        public static string Display_BgmPreviewStop {
            get {
                return ResourceManager.GetString("Display_BgmPreviewStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominator.
        /// </summary>
        public static string Display_Denominator {
            get {
                return ResourceManager.GetString("Display_Denominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        public static string Display_Designer {
            get {
                return ResourceManager.GetString("Display_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Display_Difficulty {
            get {
                return ResourceManager.GetString("Display_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display BPM.
        /// </summary>
        public static string Display_DisplayBPM {
            get {
                return ResourceManager.GetString("Display_DisplayBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Blank Measure.
        /// </summary>
        public static string Display_InsertBlankMeasure {
            get {
                return ResourceManager.GetString("Display_InsertBlankMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Custom Background.
        /// </summary>
        public static string Display_IsCustomBackground {
            get {
                return ResourceManager.GetString("Display_IsCustomBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket File.
        /// </summary>
        public static string Display_JacketFile {
            get {
                return ResourceManager.GetString("Display_JacketFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Display_Level {
            get {
                return ResourceManager.GetString("Display_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Timeline.
        /// </summary>
        public static string Display_MainTil {
            get {
                return ResourceManager.GetString("Display_MainTil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Offset (s).
        /// </summary>
        public static string Display_ManualOffset {
            get {
                return ResourceManager.GetString("Display_ManualOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Field Line Color.
        /// </summary>
        public static string Display_NotesFieldLine {
            get {
                return ResourceManager.GetString("Display_NotesFieldLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerator.
        /// </summary>
        public static string Display_Numerator {
            get {
                return ResourceManager.GetString("Display_Numerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Offset (s).
        /// </summary>
        public static string Display_RealOffset {
            get {
                return ResourceManager.GetString("Display_RealOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string Display_ReleaseDate {
            get {
                return ResourceManager.GetString("Display_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song ID.
        /// </summary>
        public static string Display_SongId {
            get {
                return ResourceManager.GetString("Display_SongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Name.
        /// </summary>
        public static string Display_SortName {
            get {
                return ResourceManager.GetString("Display_SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage ID.
        /// </summary>
        public static string Display_StageId {
            get {
                return ResourceManager.GetString("Display_StageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick.
        /// </summary>
        public static string Display_Tick {
            get {
                return ResourceManager.GetString("Display_Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Display_Title {
            get {
                return ResourceManager.GetString("Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World&apos;s End Difficulty.
        /// </summary>
        public static string Display_WorldsEndDifficulty {
            get {
                return ResourceManager.GetString("Display_WorldsEndDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World&apos;s End Event ID.
        /// </summary>
        public static string Display_WorldsEndEventID {
            get {
                return ResourceManager.GetString("Display_WorldsEndEventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World&apos;s End Tag.
        /// </summary>
        public static string Display_WorldsEndTag {
            get {
                return ResourceManager.GetString("Display_WorldsEndTag", resourceCulture);
            }
        }
    }
}
