//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinguTools.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinguTools.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Button_Convert {
            get {
                return ResourceManager.GetString("Button_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Exception.
        /// </summary>
        public static string Button_Copy_Exception {
            get {
                return ResourceManager.GetString("Button_Copy_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract *.dds from *.afb.
        /// </summary>
        public static string Button_extract_dds_from_afb {
            get {
                return ResourceManager.GetString("Button_extract_dds_from_afb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Button_Generate {
            get {
                return ResourceManager.GetString("Button_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Temp Directory.
        /// </summary>
        public static string Button_open_temp_directory {
            get {
                return ResourceManager.GetString("Button_open_temp_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recollect A000.
        /// </summary>
        public static string Button_Recollect_A000 {
            get {
                return ResourceManager.GetString("Button_Recollect_A000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        public static string Button_Show_Details {
            get {
                return ResourceManager.GetString("Button_Show_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta is not set..
        /// </summary>
        public static string Error_meta_is_not_set {
            get {
                return ResourceManager.GetString("Error_meta_is_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error_Unhandled {
            get {
                return ResourceManager.GetString("Error_Unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background (1920×1080): .
        /// </summary>
        public static string Label_Background {
            get {
                return ResourceManager.GetString("Label_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart: .
        /// </summary>
        public static string Label_Chart {
            get {
                return ResourceManager.GetString("Label_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culprit.
        /// </summary>
        public static string Label_Culprit {
            get {
                return ResourceManager.GetString("Label_Culprit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects (256×256).
        /// </summary>
        public static string Label_Effects {
            get {
                return ResourceManager.GetString("Label_Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Label_Information {
            get {
                return ResourceManager.GetString("Label_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input: .
        /// </summary>
        public static string Label_Input {
            get {
                return ResourceManager.GetString("Label_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket ID.
        /// </summary>
        public static string Label_Jacket_ID {
            get {
                return ResourceManager.GetString("Label_Jacket_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Label_Message {
            get {
                return ResourceManager.GetString("Label_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string Label_Not_Available {
            get {
                return ResourceManager.GetString("Label_Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Field Line Color.
        /// </summary>
        public static string Label_NotesField_Line_Color {
            get {
                return ResourceManager.GetString("Label_NotesField_Line_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Label_Parameters {
            get {
                return ResourceManager.GetString("Label_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        public static string Label_StackTrace {
            get {
                return ResourceManager.GetString("Label_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage ID.
        /// </summary>
        public static string Label_Stage_ID {
            get {
                return ResourceManager.GetString("Label_Stage_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting....
        /// </summary>
        public static string Status_collecting {
            get {
                return ResourceManager.GetString("Status_collecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string Status_done {
            get {
                return ResourceManager.GetString("Status_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Status_error {
            get {
                return ResourceManager.GetString("Status_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Status_idle {
            get {
                return ResourceManager.GetString("Status_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Status_saving {
            get {
                return ResourceManager.GetString("Status_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string Status_starting {
            get {
                return ResourceManager.GetString("Status_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Tab_Chart {
            get {
                return ResourceManager.GetString("Tab_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket.
        /// </summary>
        public static string Tab_Jacket {
            get {
                return ResourceManager.GetString("Tab_Jacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string Tab_Misc {
            get {
                return ResourceManager.GetString("Tab_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Tab_Music {
            get {
                return ResourceManager.GetString("Tab_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string Tab_Stage {
            get {
                return ResourceManager.GetString("Tab_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string Tab_Workflow {
            get {
                return ResourceManager.GetString("Tab_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string Title_Diagnostics {
            get {
                return ResourceManager.GetString("Title_Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the A000 folder.
        /// </summary>
        public static string Title_select_the_A000_folder {
            get {
                return ResourceManager.GetString("Title_select_the_A000_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the input file.
        /// </summary>
        public static string Title_select_the_input_file {
            get {
                return ResourceManager.GetString("Title_select_the_input_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the output folder.
        /// </summary>
        public static string Title_select_the_output_folder {
            get {
                return ResourceManager.GetString("Title_select_the_output_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already the latest version.
        /// </summary>
        public static string UpdateCheck_Already_Latest {
            get {
                return ResourceManager.GetString("UpdateCheck_Already_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string UpdateCheck_Checking {
            get {
                return ResourceManager.GetString("UpdateCheck_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check failed.
        /// </summary>
        public static string UpdateCheck_Failed {
            get {
                return ResourceManager.GetString("UpdateCheck_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version {0} available (Click to View).
        /// </summary>
        public static string UpdateCheck_New_Version_Available {
            get {
                return ResourceManager.GetString("UpdateCheck_New_Version_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to check for updates.
        /// </summary>
        public static string UpdateCheck_Tooltip {
            get {
                return ResourceManager.GetString("UpdateCheck_Tooltip", resourceCulture);
            }
        }
    }
}
