//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinguTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinguTools.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please edit the properties of charts in Margrete first..
        /// </summary>
        public static string Alert_edit_notice {
            get {
                return ResourceManager.GetString("Alert_edit_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has been modified on {0:HH:mm:ss}. Reload to use the latest version..
        /// </summary>
        public static string Alert_file_changed {
            get {
                return ResourceManager.GetString("Alert_file_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommended to edit chart properties in Margrete first..
        /// </summary>
        public static string Alert_mgxc_edit_recommend {
            get {
                return ResourceManager.GetString("Alert_mgxc_edit_recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Button_Convert {
            get {
                return ResourceManager.GetString("Button_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Exception.
        /// </summary>
        public static string Button_Copy_Exception {
            get {
                return ResourceManager.GetString("Button_Copy_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract *.dds from *.afb.
        /// </summary>
        public static string Button_extract_dds_from_afb {
            get {
                return ResourceManager.GetString("Button_extract_dds_from_afb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Button_Generate {
            get {
                return ResourceManager.GetString("Button_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Temp Directory.
        /// </summary>
        public static string Button_open_temp_directory {
            get {
                return ResourceManager.GetString("Button_open_temp_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recollect A000.
        /// </summary>
        public static string Button_Recollect_A000 {
            get {
                return ResourceManager.GetString("Button_Recollect_A000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Button_Reload {
            get {
                return ResourceManager.GetString("Button_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGM.
        /// </summary>
        public static string Category_BGM {
            get {
                return ResourceManager.GetString("Category_BGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Category_Chart {
            get {
                return ResourceManager.GetString("Category_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Category_Display {
            get {
                return ResourceManager.GetString("Category_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string Category_Misc {
            get {
                return ResourceManager.GetString("Category_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Category_Settings {
            get {
                return ResourceManager.GetString("Category_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string Category_Song {
            get {
                return ResourceManager.GetString("Category_Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Category_Sync {
            get {
                return ResourceManager.GetString("Category_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible w/ Margrete {0}.
        /// </summary>
        public static string Compatible_with_Margrete {
            get {
                return ResourceManager.GetString("Compatible_with_Margrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field determines the background stage in the game. To quickly set it up, include &quot;#meta stage [StringID]&quot; in the chart comment (Replace [StringID] with the stage&apos;s ID or name)..
        /// </summary>
        public static string Description_BackgroundStage {
            get {
                return ResourceManager.GetString("Description_BackgroundStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommended to use audio files in .wav format to reduce the audio latency discrepancy between the game and Margrete, .
        /// </summary>
        public static string Description_BgmFile {
            get {
                return ResourceManager.GetString("Description_BgmFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the starting BPM (Beats Per Minute) of the chart. It is used to calculate real offset..
        /// </summary>
        public static string Description_BgmInitialBpm {
            get {
                return ResourceManager.GetString("Description_BgmInitialBpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the time signature (beats per bar and note value) at the start of the chart. It is used to calculate real offset..
        /// </summary>
        public static string Description_BgmInitialTimeSignature {
            get {
                return ResourceManager.GetString("Description_BgmInitialTimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM displayed in song selection menu.
        /// </summary>
        public static string Description_DisplayBPM {
            get {
                return ResourceManager.GetString("Description_DisplayBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To quickly set it up, include &quot;#meta genre [StringID]&quot; in the chart comment (Replace [StringID] with the stage&apos;s ID or name)..
        /// </summary>
        public static string Description_Genre {
            get {
                return ResourceManager.GetString("Description_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure this through Margrete (Insert a blank bar before the first measure). If enabled, a silent measure with click cues is inserted at the beginning, ensuring that the first musical measure follows the blank..
        /// </summary>
        public static string Description_InsertBlankMeasure {
            get {
                return ResourceManager.GetString("Description_InsertBlankMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to specify which difficulty&apos;s chart property will be used as the reference..
        /// </summary>
        public static string Description_MainDifficulty {
            get {
                return ResourceManager.GetString("Description_MainDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure this through Margrete (Base timeline). Determines which Timeline affects the bar line positions and AIR animation speed. Default is 0..
        /// </summary>
        public static string Description_MainTil {
            get {
                return ResourceManager.GetString("Description_MainTil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure this through Margrete. This value represents the offset (in seconds) applied to the song manually set by user. Positive values indicate a delay, while negative values indicate an advance..
        /// </summary>
        public static string Description_ManualOffset {
            get {
                return ResourceManager.GetString("Description_ManualOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the number of files that can be converted simultaneously. Increasing this value will speed up overall conversion, but may also increase the likelihood of audio conversion exceptions..
        /// </summary>
        public static string Description_MaxParallelismDegree {
            get {
                return ResourceManager.GetString("Description_MaxParallelismDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts BGM files to 16-bit, 48kHz PCM .wav format and normalizes loudness. You can disable this if your files are already in the correct format. To quickly set it up, include &quot;#meta normalize false&quot; in the chart comment..
        /// </summary>
        public static string Description_NormalizeBgm {
            get {
                return ResourceManager.GetString("Description_NormalizeBgm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value represents the calculated offset (in seconds) applied to the song. Positive values indicate a delay, while negative values indicate an advance..
        /// </summary>
        public static string Description_RealOffset {
            get {
                return ResourceManager.GetString("Description_RealOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Song ID is extracted from Margrete&apos;s Song ID..
        /// </summary>
        public static string Description_SongId {
            get {
                return ResourceManager.GetString("Description_SongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how songs are sorted in the game..
        /// </summary>
        public static string Description_SortName {
            get {
                return ResourceManager.GetString("Description_SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event that unlocks the &quot;World&apos;s End&quot; or &quot;ULTIMA&quot; chart in the game. If left blank, the generation of the associated Event.xml file will be skipped..
        /// </summary>
        public static string Description_UnlockEventID {
            get {
                return ResourceManager.GetString("Description_UnlockEventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event that unlocks the &quot;World&apos;s End&quot; or &quot;ULTIMA&quot; charts in the game..
        /// </summary>
        public static string Description_UnlockEventIDOption {
            get {
                return ResourceManager.GetString("Description_UnlockEventIDOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple charts with the same song ID and difficulty exist, the last scanned file will be used..
        /// </summary>
        public static string Diag_duplicate_id_and_difficulty {
            get {
                return ResourceManager.GetString("Diag_duplicate_id_and_difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is ignored since Song ID is missing. Set a number for Song Id in Margrete..
        /// </summary>
        public static string Diag_file_ignored_due_to_id_missing {
            get {
                return ResourceManager.GetString("Diag_file_ignored_due_to_id_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple charts for this Song ID have been tagged with “#meta main” in their comments. The first chart found with this tag will be set as the reference difficulty..
        /// </summary>
        public static string Diag_more_than_one_chart_marked_main {
            get {
                return ResourceManager.GetString("Diag_more_than_one_chart_marked_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reference difficulty for this Song ID. Selecting the highest-difficulty chart by default. To choose a reference difficulty explicitly, add `#meta main` to the comment of the chart..
        /// </summary>
        public static string Diag_no_chart_marked_main {
            get {
                return ResourceManager.GetString("Diag_no_chart_marked_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World&apos;s End chart must use unique Song ID; otherwise, other difficulty charts will not display under common song categories..
        /// </summary>
        public static string Diag_we_chart_must_be_unique_id {
            get {
                return ResourceManager.GetString("Diag_we_chart_must_be_unique_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Display_Artist {
            get {
                return ResourceManager.GetString("Display_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background File.
        /// </summary>
        public static string Display_BackgroundFile {
            get {
                return ResourceManager.GetString("Display_BackgroundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Stage.
        /// </summary>
        public static string Display_BackgroundStage {
            get {
                return ResourceManager.GetString("Display_BackgroundStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGM File.
        /// </summary>
        public static string Display_BgmFile {
            get {
                return ResourceManager.GetString("Display_BgmFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial BPM.
        /// </summary>
        public static string Display_BgmInitialBpm {
            get {
                return ResourceManager.GetString("Display_BgmInitialBpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Time Signature.
        /// </summary>
        public static string Display_BgmInitialTimeSignature {
            get {
                return ResourceManager.GetString("Display_BgmInitialTimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Start Time (s).
        /// </summary>
        public static string Display_BgmPreviewStart {
            get {
                return ResourceManager.GetString("Display_BgmPreviewStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Stop Time (s).
        /// </summary>
        public static string Display_BgmPreviewStop {
            get {
                return ResourceManager.GetString("Display_BgmPreviewStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Audio.
        /// </summary>
        public static string Display_ConvertAudio {
            get {
                return ResourceManager.GetString("Display_ConvertAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Background.
        /// </summary>
        public static string Display_ConvertBackground {
            get {
                return ResourceManager.GetString("Display_ConvertBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Chart.
        /// </summary>
        public static string Display_ConvertChart {
            get {
                return ResourceManager.GetString("Display_ConvertChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Jacket.
        /// </summary>
        public static string Display_ConvertJacket {
            get {
                return ResourceManager.GetString("Display_ConvertJacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominator.
        /// </summary>
        public static string Display_Denominator {
            get {
                return ResourceManager.GetString("Display_Denominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        public static string Display_Designer {
            get {
                return ResourceManager.GetString("Display_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Display_Difficulty {
            get {
                return ResourceManager.GetString("Display_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display BPM.
        /// </summary>
        public static string Display_DisplayBPM {
            get {
                return ResourceManager.GetString("Display_DisplayBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string Display_FilePath {
            get {
                return ResourceManager.GetString("Display_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Event.xml.
        /// </summary>
        public static string Display_GenerateEventXml {
            get {
                return ResourceManager.GetString("Display_GenerateEventXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Music.xml.
        /// </summary>
        public static string Display_GenerateMusicXml {
            get {
                return ResourceManager.GetString("Display_GenerateMusicXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Display_Genre {
            get {
                return ResourceManager.GetString("Display_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Blank Measure.
        /// </summary>
        public static string Display_InsertBlankMeasure {
            get {
                return ResourceManager.GetString("Display_InsertBlankMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Background.
        /// </summary>
        public static string Display_IsCustomStage {
            get {
                return ResourceManager.GetString("Display_IsCustomStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket File.
        /// </summary>
        public static string Display_JacketFile {
            get {
                return ResourceManager.GetString("Display_JacketFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Display_Level {
            get {
                return ResourceManager.GetString("Display_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced Difficulty.
        /// </summary>
        public static string Display_MainDifficulty {
            get {
                return ResourceManager.GetString("Display_MainDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Timeline.
        /// </summary>
        public static string Display_MainTil {
            get {
                return ResourceManager.GetString("Display_MainTil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Offset (s).
        /// </summary>
        public static string Display_ManualOffset {
            get {
                return ResourceManager.GetString("Display_ManualOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Parallel Tasks.
        /// </summary>
        public static string Display_MaxParallelismDegree {
            get {
                return ResourceManager.GetString("Display_MaxParallelismDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalize Bgm Format.
        /// </summary>
        public static string Display_NormalizeBgm {
            get {
                return ResourceManager.GetString("Display_NormalizeBgm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Field Line Color.
        /// </summary>
        public static string Display_NotesFieldLine {
            get {
                return ResourceManager.GetString("Display_NotesFieldLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerator.
        /// </summary>
        public static string Display_Numerator {
            get {
                return ResourceManager.GetString("Display_Numerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Name.
        /// </summary>
        public static string Display_OptionName {
            get {
                return ResourceManager.GetString("Display_OptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Offset (s).
        /// </summary>
        public static string Display_RealOffset {
            get {
                return ResourceManager.GetString("Display_RealOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string Display_ReleaseDate {
            get {
                return ResourceManager.GetString("Display_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song ID.
        /// </summary>
        public static string Display_SongId {
            get {
                return ResourceManager.GetString("Display_SongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Name.
        /// </summary>
        public static string Display_SortName {
            get {
                return ResourceManager.GetString("Display_SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage ID.
        /// </summary>
        public static string Display_StageId {
            get {
                return ResourceManager.GetString("Display_StageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick.
        /// </summary>
        public static string Display_Tick {
            get {
                return ResourceManager.GetString("Display_Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Display_Title {
            get {
                return ResourceManager.GetString("Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Ultima Event ID.
        /// </summary>
        public static string Display_UltimaEventId {
            get {
                return ResourceManager.GetString("Display_UltimaEventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Event ID.
        /// </summary>
        public static string Display_UnlockEventID {
            get {
                return ResourceManager.GetString("Display_UnlockEventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock World&apos;s End Event ID.
        /// </summary>
        public static string Display_WeEventId {
            get {
                return ResourceManager.GetString("Display_WeEventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World&apos;s End Difficulty.
        /// </summary>
        public static string Display_WorldsEndDifficulty {
            get {
                return ResourceManager.GetString("Display_WorldsEndDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World&apos;s End Tag.
        /// </summary>
        public static string Display_WorldsEndTag {
            get {
                return ResourceManager.GetString("Display_WorldsEndTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * But nobody came..
        /// </summary>
        public static string Error_but_nobody_came {
            get {
                return ResourceManager.GetString("Error_but_nobody_came", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart conversion failed..
        /// </summary>
        public static string Error_Chart_Failed {
            get {
                return ResourceManager.GetString("Error_Chart_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket conversion failed..
        /// </summary>
        public static string Error_Jacket_Failed {
            get {
                return ResourceManager.GetString("Error_Jacket_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music conversion failed..
        /// </summary>
        public static string Error_Music_Failed {
            get {
                return ResourceManager.GetString("Error_Music_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No charts are found in the directory..
        /// </summary>
        public static string Error_no_charts_are_found_directory {
            get {
                return ResourceManager.GetString("Error_no_charts_are_found_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage conversion failed..
        /// </summary>
        public static string Error_Stage_Failed {
            get {
                return ResourceManager.GetString("Error_Stage_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio: .
        /// </summary>
        public static string Label_Audio {
            get {
                return ResourceManager.GetString("Label_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background (1920×1080): .
        /// </summary>
        public static string Label_Background {
            get {
                return ResourceManager.GetString("Label_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart: .
        /// </summary>
        public static string Label_Chart {
            get {
                return ResourceManager.GetString("Label_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Label_Details {
            get {
                return ResourceManager.GetString("Label_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects (256×256).
        /// </summary>
        public static string Label_Effects {
            get {
                return ResourceManager.GetString("Label_Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder: .
        /// </summary>
        public static string Label_Folder {
            get {
                return ResourceManager.GetString("Label_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image: .
        /// </summary>
        public static string Label_Image {
            get {
                return ResourceManager.GetString("Label_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket ID.
        /// </summary>
        public static string Label_Jacket_ID {
            get {
                return ResourceManager.GetString("Label_Jacket_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Label_Message {
            get {
                return ResourceManager.GetString("Label_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string Label_Not_Available {
            get {
                return ResourceManager.GetString("Label_Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Field Line Color.
        /// </summary>
        public static string Label_NotesField_Line_Color {
            get {
                return ResourceManager.GetString("Label_NotesField_Line_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Label_Parameters {
            get {
                return ResourceManager.GetString("Label_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Label_Path {
            get {
                return ResourceManager.GetString("Label_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Label_Preview {
            get {
                return ResourceManager.GetString("Label_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Label_Properties {
            get {
                return ResourceManager.GetString("Label_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Label_Settings {
            get {
                return ResourceManager.GetString("Label_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        public static string Label_StackTrace {
            get {
                return ResourceManager.GetString("Label_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage ID.
        /// </summary>
        public static string Label_Stage_ID {
            get {
                return ResourceManager.GetString("Label_Stage_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Label_Time {
            get {
                return ResourceManager.GetString("Label_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to discard the changes?.
        /// </summary>
        public static string Message_discard_changes {
            get {
                return ResourceManager.GetString("Message_discard_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting {0}/{1}... .
        /// </summary>
        public static string Status_convert_progress {
            get {
                return ResourceManager.GetString("Status_convert_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Tab_Chart {
            get {
                return ResourceManager.GetString("Tab_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacket.
        /// </summary>
        public static string Tab_Jacket {
            get {
                return ResourceManager.GetString("Tab_Jacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string Tab_Misc {
            get {
                return ResourceManager.GetString("Tab_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Tab_Music {
            get {
                return ResourceManager.GetString("Tab_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string Tab_Option {
            get {
                return ResourceManager.GetString("Tab_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string Tab_Stage {
            get {
                return ResourceManager.GetString("Tab_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string Tab_Workflow {
            get {
                return ResourceManager.GetString("Tab_Workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string Title_Diagnostics {
            get {
                return ResourceManager.GetString("Title_Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the A000 folder.
        /// </summary>
        public static string Title_select_the_A000_folder {
            get {
                return ResourceManager.GetString("Title_select_the_A000_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the input file.
        /// </summary>
        public static string Title_select_the_input_file {
            get {
                return ResourceManager.GetString("Title_select_the_input_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the output folder.
        /// </summary>
        public static string Title_select_the_output_folder {
            get {
                return ResourceManager.GetString("Title_select_the_output_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already the latest version.
        /// </summary>
        public static string UpdateCheck_Already_Latest {
            get {
                return ResourceManager.GetString("UpdateCheck_Already_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string UpdateCheck_Checking {
            get {
                return ResourceManager.GetString("UpdateCheck_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check failed.
        /// </summary>
        public static string UpdateCheck_Failed {
            get {
                return ResourceManager.GetString("UpdateCheck_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version {0} available (Click to View).
        /// </summary>
        public static string UpdateCheck_New_Version_Available {
            get {
                return ResourceManager.GetString("UpdateCheck_New_Version_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to check for updates.
        /// </summary>
        public static string UpdateCheck_Tooltip {
            get {
                return ResourceManager.GetString("UpdateCheck_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
