name: "build release"

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Cache Cargo
        id: cache-cargo
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          save-always: true
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install "cargo-c"
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: "cargo install cargo-c"

      - name: Initialize Submodules
        run: git submodule update --init --recursive

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10"

      - name: Restore Nuget Packages
        run: dotnet restore

      - name: Publish .NET Application (Self-Contained)
        run: dotnet publish -c Release -r win-x64 --self-contained true --artifacts-path ./Build/Self-Contained

      - name: Publish .NET Application (Framework-Dependent)
        run: dotnet publish -c Release -r win-x64 --self-contained false --artifacts-path ./Build/Framework-Dependent

      - name: Prepare Self-Contained Artifact
        run: |
          $tagName = $env:GITHUB_REF -replace 'refs/(heads|tags|remotes)/', ''
          New-Item -ItemType Directory -Path Build/artifacts
          Copy-Item "Build/Self-Contained/publish/PinguTools/release_win-x64/PinguTools.exe" "Build/artifacts/PinguTools_${tagName}_Self_Contained.exe"

      - name: Prepare Framework-Dependent Artifact
        run: |
          $tagName = $env:GITHUB_REF -replace 'refs/(heads|tags|remotes)/', ''
          Copy-Item "Build/Framework-Dependent/publish/PinguTools/release_win-x64/PinguTools.exe" "Build/artifacts/PinguTools_${tagName}.exe"

      - name: Action Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Build/artifacts/*
            LICENSE
            THIRD-PARTY-NOTICES.md